### ISSUE TITLE
Regional figures of England being repeated

### ISSUE THREAD

**Issue by varunjakki** [ONSdigital/sdg_data_updates#14]
Regional figures of England are being repeated - Regional figures with GeoCodes E12000001- E12000009 NOT layered with sector or sex are being repeated when 'dissagregation_data_for_calculations' and 'headline_data_for_calculations' are binded on line 118.  However they have different values for 'Total employment' and 'informal employment' - which is weird as they represent the same thing in both df meaning these numbers should be the same.

@EmmaWoodONS

**Comment by EmmaWoodONS** [comment]
Well spotted @varunjakki!

I edited the block of code at 112 to be: 
```
headline_data_for_calculations <- disaggregation_data_for_calculations %>% 
  filter(is.na(SEX)) %>% # had to filter out male-only and female-only figures so we didn't double count them
  group_by(Sector) %>% # grouping by Sector because we want a figure for each of agriculture, non-ag, and total
  summarise(Total_employment = sum(Total_employment),
            informal_employment = sum(informal_employment), .groups = 'drop')
```
We were getting a larger number in the 'headline' df because of double counting sectors

**Comment by EmmaWoodONS** [comment]
I will upload my changes to the branch in a bit, so if you work on it again later, you'll need to do a fetch
