### ISSUE TITLE
8-3-1 edits required

### ISSUE THREAD

**Issue by EmmaWoodONS** [ONSdigital/sdg_data_updates#23]
- Don't suppress num of people in employment unless that count is lower than 3
- East not East of England
- South West not South west
- Percentage not proportion
- Add rows for the missing regions
- add totals to country by sex
- Make sex order Men, Women, Total

**Comment by varunjakki** [comment]
All issues addressed and fixed in last push on 27/04/2021 in 'final_big_push' branch

**Comment by EmmaWoodONS** [comment]
Still to do in code (done manually in Excel for now): 
- [ ] R markdown report
- [ ] 'low' in cells that round to 0 
- [ ] footnote about the point above
- [ ] check that all tabs contain the relevant footnotes regarding shaded and suppressed cells. For this and the point about zeros, automate it so the footnote is only given when it is relevant for the tab
